# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pos_dict.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'pos_dict.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epos_dict.proto\x12\x0bhtpostagger\"\xb9\x01\n\x07PosDict\x12*\n\x03p2i\x18\x01 \x03(\x0b\x32\x1d.htpostagger.PosDict.P2iEntry\x12*\n\x03i2p\x18\x02 \x03(\x0b\x32\x1d.htpostagger.PosDict.I2pEntry\x1a*\n\x08P2iEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x1a*\n\x08I2pEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pos_dict_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSDICT_P2IENTRY']._loaded_options = None
  _globals['_POSDICT_P2IENTRY']._serialized_options = b'8\001'
  _globals['_POSDICT_I2PENTRY']._loaded_options = None
  _globals['_POSDICT_I2PENTRY']._serialized_options = b'8\001'
  _globals['_POSDICT']._serialized_start=32
  _globals['_POSDICT']._serialized_end=217
  _globals['_POSDICT_P2IENTRY']._serialized_start=131
  _globals['_POSDICT_P2IENTRY']._serialized_end=173
  _globals['_POSDICT_I2PENTRY']._serialized_start=175
  _globals['_POSDICT_I2PENTRY']._serialized_end=217
# @@protoc_insertion_point(module_scope)
