# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tok_dict.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'tok_dict.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etok_dict.proto\x12\x0bhttokenizer\"d\n\x07TokDict\x12,\n\x04\x64ict\x18\x01 \x03(\x0b\x32\x1e.httokenizer.TokDict.DictEntry\x1a+\n\tDictEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tok_dict_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOKDICT_DICTENTRY']._loaded_options = None
  _globals['_TOKDICT_DICTENTRY']._serialized_options = b'8\001'
  _globals['_TOKDICT']._serialized_start=31
  _globals['_TOKDICT']._serialized_end=131
  _globals['_TOKDICT_DICTENTRY']._serialized_start=88
  _globals['_TOKDICT_DICTENTRY']._serialized_end=131
# @@protoc_insertion_point(module_scope)
